apiVersion: apps/v1
kind: Deployment
metadata:
  name: faizulkarim-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faizulkarim-springboot
  template:
    metadata:
      labels:
        app: faizulkarim-springboot
    spec:
      containers:
        - name: springboot
          image: faizulkarimsunnygit/springboot-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: faizulkarim-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: faizulkarim-springboot
